FROM node:20-slim

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy ingest service
COPY http-mongo-service.js ./

# Expose port for the HTTP service
EXPOSE 3001

CMD ["node", "http-mongo-service.js"]
